name: Run linters

on: [push, pull_request]

jobs:
  revive-lint:
    name: Revive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run Revive
        uses: docker://morphy/revive-action:v2
        with:
          config: .revive.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golang-ci-lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.62.2
